const keyboardMap = {
  b: "BUBBLE_GAME",
  c: "COLOR_SPLASH",
  i: "ILLUSION",
  s: "SOUND_BOARD",
  m: "MOTION_PLAY",
  l: "LIGHT_TRAILS",
  p: "PATTERN_FLOW",
  g: "SHAPE_TAP_GAME",
  w: "WAVY_MIRROR",
  r: "RAINBOW_RAIN",
  d: "DANCING_DOTS",
  f: "FLOATING_SHAPES",
  t: "TWINKLING_STARS",
  h: "HAPPY_FACES",
  o: "ORBITING_PLANETS",
  k: "KALEIDOSCOPE",
  x: "XYLOPHONE",
  v: "COLOR_BLOCKS",
  z: "ZOOMING_LINES",

  "1": "BUBBLE_GAME",
  "2": "RAINBOW_RAIN",
  "3": "DANCING_DOTS",
  "4": "TWINKLING_STARS",
  "5": "FLOATING_SHAPES",
  "6": "COLOR_BLOCKS",
  "7": "SHAPE_TAP_GAME",
  "8": "LIGHT_TRAILS",
  "9": "MOTION_PLAY",
  "0": "KALEIDOSCOPE",

  enter: "FIREWORKS",
  escape: "EMOJI_RAIN",
  backspace: "PIXEL_WAVES",
  tab: "COIN_CATCH",
  " ": "CONFETTI_STORM",
  arrowup: "PIXEL_WAVES",
  arrowdown: "CONFETTI_STORM",
  arrowleft: "FIREWORKS",
  arrowright: "EMOJI_RAIN",
  capslock: "RAINBOW_RAIN",

  f1: "BUBBLE_GAME",
  f2: "RAINBOW_RAIN",
  f3: "DANCING_DOTS",
  f4: "TWINKLING_STARS",
  f5: "FLOATING_SHAPES",
  f6: "COLOR_BLOCKS",
  f7: "SHAPE_TAP_GAME",
  f8: "LIGHT_TRAILS",
  f9: "MOTION_PLAY",
  f10: "KALEIDOSCOPE",
  f11: "FIREWORKS",
  f12: "CONFETTI_STORM",
};

export default keyboardMap;
